"""Enumerations used by the CSA Assessment Console."""

from __future__ import annotations

from enum import Enum


class CollectorMode(str, Enum):
    """Supported endpoint collection modes."""

    STANDARD_USER_COLLECTION = "STANDARD_USER_COLLECTION"
    ELEVATED_COLLECTION = "ELEVATED_COLLECTION"
    ACTIVE_VALIDATION = "ACTIVE_VALIDATION"


class PrivilegeKind(str, Enum):
    """Effective Windows execution contexts."""

    STANDARD_USER = "STANDARD_USER"
    ADMIN_MEMBER_NOT_ELEVATED = "ADMIN_MEMBER_NOT_ELEVATED"
    ELEVATED_ADMINISTRATOR = "ELEVATED_ADMINISTRATOR"
    SYSTEM = "SYSTEM"
    UNKNOWN = "UNKNOWN"


class MinimumPrivilege(str, Enum):
    """Minimum privilege declared by a collection capability."""

    STANDARD_USER = "STANDARD_USER"
    ELEVATED_ADMINISTRATOR = "ELEVATED_ADMINISTRATOR"


class CapabilityStatus(str, Enum):
    """Terminal capability collection states."""

    COLLECTED = "COLLECTED"
    COLLECTED_PARTIAL = "COLLECTED_PARTIAL"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    NOT_COLLECTED_PRIVILEGE_REQUIRED = "NOT_COLLECTED_PRIVILEGE_REQUIRED"
    NOT_COLLECTED_POLICY_BLOCKED = "NOT_COLLECTED_POLICY_BLOCKED"
    NOT_COLLECTED_TIMEOUT = "NOT_COLLECTED_TIMEOUT"
    NOT_COLLECTED_ACCESS_DENIED = "NOT_COLLECTED_ACCESS_DENIED"
    NOT_COLLECTED_ERROR = "NOT_COLLECTED_ERROR"


class SessionStatus(str, Enum):
    """Assessment session lifecycle states."""

    DRAFT = "DRAFT"
    OPEN = "OPEN"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class AssessmentStatus(str, Enum):
    """Assessment lifecycle states."""

    OPEN = "OPEN"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class SubmissionState(str, Enum):
    """Submission pipeline and terminal failure states."""

    RECEIVED = "RECEIVED"
    QUARANTINED = "QUARANTINED"
    TRANSPORT_VALIDATED = "TRANSPORT_VALIDATED"
    INTEGRITY_VALIDATED = "INTEGRITY_VALIDATED"
    SCHEMA_VALIDATED = "SCHEMA_VALIDATED"
    PRIVACY_SCANNED = "PRIVACY_SCANNED"
    EVIDENCE_ACCEPTED = "EVIDENCE_ACCEPTED"
    ANALYZED = "ANALYZED"
    REPORTED = "REPORTED"
    REJECTED_SESSION_CLOSED = "REJECTED_SESSION_CLOSED"
    REJECTED_EXPIRED = "REJECTED_EXPIRED"
    REJECTED_UNAUTHORIZED_SOURCE = "REJECTED_UNAUTHORIZED_SOURCE"
    REJECTED_TOKEN = "REJECTED_TOKEN"
    REJECTED_REPLAY = "REJECTED_REPLAY"
    REJECTED_PACKAGE_LIMIT = "REJECTED_PACKAGE_LIMIT"
    REJECTED_ARCHIVE_SAFETY = "REJECTED_ARCHIVE_SAFETY"
    REJECTED_DIGEST = "REJECTED_DIGEST"
    REJECTED_SCHEMA = "REJECTED_SCHEMA"
    REJECTED_SENSITIVE_DATA = "REJECTED_SENSITIVE_DATA"
    REJECTED_UNTRUSTED_COLLECTOR = "REJECTED_UNTRUSTED_COLLECTOR"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"


class CoverageDomain(str, Enum):
    """Canonical endpoint assessment coverage domains."""

    OS = "OS"
    PATCHING = "PATCHING"
    SOFTWARE = "SOFTWARE"
    ENDPOINT_PROTECTION = "ENDPOINT_PROTECTION"
    DISK_ENCRYPTION = "DISK_ENCRYPTION"
    IDENTITY = "IDENTITY"
    NETWORK = "NETWORK"
    SECURITY_POLICY = "SECURITY_POLICY"
    BROWSER = "BROWSER"
    SERVICES = "SERVICES"
    CERTIFICATES = "CERTIFICATES"
    ACTIVE_VALIDATION = "ACTIVE_VALIDATION"
